import type { Metadata } from "next";
import { Gantari } from "next/font/google";
import "./globals.css";

const gantari = Gantari({
  variable: "--font-sans",
  subsets: ["latin"],
});

// const gantariMono = Gantari_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "SackTrack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${gantari.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>{children}</body>
    </html>
  );
}
