create table if not exists public.member_eval_criteria (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  criteria_description text,
  criteria_type text,
  is_active boolean not null default true
);

insert into public.member_eval_criteria (criteria_description, criteria_type)
select criteria_description, criteria_type
from (
  values
    ('Demonstrates accountability in assigned responsibilities', 'performance'),
    ('Communicates clearly and respectfully with the organization', 'communication'),
    ('Collaborates well with teammates and department members', 'teamwork'),
    ('Shows initiative and follows through on commitments', 'leadership'),
    ('Observes organization policies and professional conduct', 'conduct')
) as seed(criteria_description, criteria_type)
where not exists (
  select 1
  from public.member_eval_criteria existing
  where existing.criteria_description = seed.criteria_description
);

create table if not exists public.member_evaluation_response (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  evaluator_id uuid not null,
  target_user_id uuid not null,
  user_role text not null,
  user_department text,
  target_role text not null,
  target_department text,
  status text not null default 'submitted'
);

create table if not exists public.member_evaluation_answer (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  member_response_id bigint not null references public.member_evaluation_response(id) on delete cascade,
  criteria_id bigint references public.member_eval_criteria(id),
  rating_value numeric,
  answer_text text
);

create table if not exists public.member_evaluation_attempt_log (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  evaluator_id uuid,
  target_user_id uuid,
  user_role text,
  user_department text,
  target_role text,
  target_department text,
  action text not null,
  result text not null,
  reason text
);

create index if not exists member_evaluation_response_evaluator_idx
  on public.member_evaluation_response(evaluator_id);

create index if not exists member_evaluation_response_target_idx
  on public.member_evaluation_response(target_user_id);

create index if not exists member_evaluation_attempt_log_evaluator_idx
  on public.member_evaluation_attempt_log(evaluator_id);
